version: "3.9"
   
services:
  django_gunicorn:
    build:
      context: .
    env_file:
      - ./market/market/.env
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:12.9-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    env_file:
      - ./market/market/.env
    expose:
      - 5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    external: true
