# Generated by Django 4.0.5 on 2022-06-20 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.UUIDField()),
                ('date', models.DateTimeField()),
                ('name', models.TextField()),
                ('offers_price', models.IntegerField(default=0)),
                ('all_offers', models.IntegerField(default=0)),
                ('is_actual', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_categories', to='api.category')),
            ],
            options={
                'unique_together': {('obj_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.UUIDField()),
                ('date', models.DateTimeField()),
                ('name', models.TextField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_actual', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_offers', to='api.category')),
            ],
            options={
                'unique_together': {('obj_id', 'date')},
            },
        ),
    ]
