# Generated by Django 4.0.5 on 2022-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_parent_alter_offer_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='obj_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='offer',
            name='obj_id',
            field=models.CharField(max_length=36),
        ),
    ]
