# Generated by Django 4.0.5 on 2022-06-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_obj_id_alter_offer_obj_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='imp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.import'),
        ),
        migrations.AddField(
            model_name='offer',
            name='imp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.import'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('obj_id', 'imp')},
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('obj_id', 'imp')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='date',
        ),
    ]
