# Generated by Django 4.0.5 on 2022-06-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_import_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.import'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='imp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.import'),
            preserve_default=False,
        ),
    ]
