# Generated by Django 4.0.5 on 2022-06-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.import'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_categories', to='api.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_offers', to='api.category'),
        ),
    ]
